source :gemcutter
gem "rails", "2.3.10"
gem "sqlite3-ruby", :require => "sqlite3"

group :development do
  # bundler requires these gems in development
  # gem "rails-footnotes"
end

group :test do
  gem 'shoulda', '2.10.3'
  gem 'factory_girl'
  gem 'transactionata', :path => '../../'
end